### PR TITLE
Update guix version

### PR DESCRIPTION
**Pull request by ROCKTAKEY**
Hi, thanks for your maintenance of this Dockerfile.
It is very useful to use guix in Docker!

I update guix to 1.4.0 and make it to use [latest commit](https://git.savannah.gnu.org/cgit/guix.git/commit/?id=6311493d7a6271bfbc51f4693857f9a12fe9965d) on guix channel.

### CODE REVIEW

**Comment by viferga** [comment]
@ROCKTAKEY Can you update the version from the readme too? In the docker command at the end.

Another thing I would like to know if after modifying this image, this repo still works: https://github.com/metacall/distributable-linux

I am letting this as a draft meanwhile this is not addressed.

**Comment by viferga** [comment]
By the way, it would be interesting to know what is your use case with this Docker image @ROCKTAKEY

**Comment by viferga** [comment]
I am checking the linux distributable.

**Comment by viferga** [comment]
It fails:
```
substitute: updating substitutes from 'https://bordeaux.guix.gnu.org'...   0.0%
substitute: updating substitutes from 'https://ci.guix.gnu.org'...   0.0%
substitute: updating substitutes from 'https://bordeaux.guix.gnu.org'...   0.0%
.building /gnu/store/0wr0dn6rshsvj10mvdgyvb06pbyqzrd3-Python-3.5.9.tar.xz.drv...
..building /gnu/store/9i7paq31yk5j2zq2rzyrrjl46if5wxwq-bash-2.05b.tar.gz.drv...
..building /gnu/store/gr4y8z26f5k3fyr7z514vkmzw7a90lc7-bash-4.4.tar.gz.drv...
..building /gnu/store/ph1mma28d3fxpjh9dzqn6xvnk3z3iqwx-binutils-2.14.tar.gz.drv...
..building /gnu/store/gzcz7cc3bgy0qfdcypgams4cvnj1xiwk-binutils-2.20.1a.tar.bz2.drv...
...building /gnu/store/sin276416r16lw4gxcv7hgz0wmwz0vvd-binutils-2.37.tar.bz2.drv...
....building /gnu/store/1n2apl1ryy3ps38689x5ka560q5xlljb-bison-3.7.6.tar.xz.drv...
.building /gnu/store/z2m9xp8cyhxchxz48bbvyl7p73qzxj8s-bootar-1a.ses.drv...
.building /gnu/store/i5sqvk9xpy5dyij03840ablwfc1k9iaf-bzip2-1.0.8.tar.gz.drv...
.building /gnu/store/8kv5h90bs99l6z9kjfb7zncy4m52y4fw-coreutils-5.0.tar.gz.drv...
..building /gnu/store/6x8g43xdhx15bzwqhl1p506pdbw6nzyy-coreutils-8.32.tar.xz.drv...
.building /gnu/store/f4v6nii425andqmd589nz1dfz1aicy4w-diffutils-3.8.tar.xz.drv...
.building /gnu/store/vfzq7flr0r56m2dxvznkcppzn5hhzlzl-expat-2.4.1.tar.xz.drv...
.building /gnu/store/m8z17h5axm4crq27zn24m6714m3s0dyd-file-5.39.tar.gz.drv...
.building /gnu/store/vspqf8yp4bna6hhmhhryfv53n16yclx5-findutils-4.8.0.tar.xz.drv...
.building /gnu/store/zf0m69flgm4zkgmqimc9kykh0xwl6lm4-flex-2.6.4.tar.gz.drv...
.building /gnu/store/aa1m8jadlhkkq3sfznk17c8md20szx0f-gash-0.2.0.tar.gz.drv...
..building /gnu/store/y87pfx0dwlzj4j0kbhj93s2i674zb2h1-gash-utils-0.1.0.tar.gz.drv...
.building /gnu/store/fqpdjv1qdskn3kvy7zx8jswnkwxsl6kq-gawk-3.0.0.tar.gz.drv...
..building /gnu/store/gpqw0skd48mssmp8hwzq2wbb1xfg0h2v-gawk-3.1.8.tar.gz.drv...
.building /gnu/store/xqc5f3ldkir492zwbvdrfiaqy710xc5f-gawk-5.1.0.tar.xz.drv...
..building /gnu/store/7aw4x4j0hihjj5alkacwf0hrryq4qdfz-gc-8.0.4.tar.gz.drv...
.building /gnu/store/3d1vw5266l81mida4yahnvff49wfi1l3-gcc-10.3.0.tar.xz.drv...
....building /gnu/store/9b94f4fdxhh9ar5pvg2hrzrx8y2cby4r-gcc-4.9.4.tar.bz2.drv...
....building /gnu/store/lqvp4xxijlsh3mvpiqsv2sc7dskd8m5q-gcc-core-2.95.3.tar.gz.drv...
..building /gnu/store/n7g29bik78y3d2ciadiwbrlhpqacjmz8-gcc-core-4.6.4.tar.gz.drv...
...building /gnu/store/jccf4aj3fb7qxshn4m0z2pfihl5qscvm-gcc-g++-4.6.4.tar.gz.drv...
.building /gnu/store/m6z55k3riacqi4bayxif9w0acy4l6qjb-gettext-0.19.8.1.tar.gz.drv...
...building /gnu/store/pl38qyydgg0rdn6z96yjf00jq8x9dc3x-glibc-2.16.0.tar.gz.drv...
....building /gnu/store/cxv82rz7a67fkp9mrlaz011rgvhbvdvx-glibc-2.2.5.tar.gz.drv...
..building /gnu/store/0hb1iv6806pbs0gs53d60p5gx5ls8gdk-glibc-2.33.tar.xz.drv...
..building /gnu/store/y9h6y6ak6j0m9sxv69xkkl62jiiqjr6a-gmp-4.3.2.tar.gz.drv...
.building /gnu/store/cv8s48k0n533x36qgjb7g9jihl4ijf23-gmp-6.0.0a.tar.xz.drv...
.building /gnu/store/b0dys0pgawkbf14lbk4jba35i9dl77cf-grep-2.0.tar.gz.drv...
.building /gnu/store/888724r6spf51x7kg0sna7fywvzbbwxk-guile-2.0.9.tar.xz.drv...
..building /gnu/store/snyx4c2s5vfjizvzmhc0gc61qcxzax3l-guile-3.0.7.tar.xz.drv...
...building /gnu/store/jixcwgk625b02vh7j65hjyml2ayvry2n-gzip-1.2.4.tar.drv...
.building /gnu/store/85382zp19wcgr48f0vgqihin876vi519-libffi-3.3.tar.gz.drv...
.building /gnu/store/8m8i8g4x2294q3hygcnap8l8g8rycvra-libunistring-0.9.10.tar.xz.drv...
.building /gnu/store/06d5as4xgiqg6xjry98nh48c83agmbh2-linux-libre-5.10.35-gnu.tar.xz.drv...
builder for `/gnu/store/06d5as4xgiqg6xjry98nh48c83agmbh2-linux-libre-5.10.35-gnu.tar.xz.drv' failed to produce output path `/gnu/store/a1sqrdsy1xrk6cs84kzgg93rw28zcaa4-linux-libre-5.10.35-gnu.tar.xz'
build of /gnu/store/06d5as4xgiqg6xjry98nh48c83agmbh2-linux-libre-5.10.35-gnu.tar.xz.drv failed
View build log at '/var/log/guix/drvs/06/d5as4xgiqg6xjry98nh48c83agmbh2-linux-libre-5.10.35-gnu.tar.xz.drv.gz'.
cannot build derivation `/gnu/store/3hkablb49p9a4gphqb2n75i31xcxdix6-linux-libre-headers-5.10.35.drv': 1 dependencies couldn't be built
building /gnu/store/sdc2grc83fkrfy85hfdab3bj9m8adkm4-linux-libre-headers-stripped-4.14.67-i686-linux.tar.xz.drv...
cannot build derivation `/gnu/store/nxlhlkjqs233kncnrg2hd7zwphbwk0ri-guile-3.0.7.drv': 1 dependencies couldn't be built
cannot build derivation `/gnu/store/iv20vqxfzsbqx5j9lzzlcy713ln4qwq4-compute-guix-derivation.drv': 1 dependencies couldn't be built
guix pull: error: build of `/gnu/store/iv20vqxfzsbqx5j9lzzlcy713ln4qwq4-compute-guix-derivation.drv' failed
make: *** [Makefile:77: pull] Error 1
```

This is the version that works for me:
```
       (commit "ef7df2ca7bb212455f1d6bbef5bbf7b1ac5a189d")) ; Tue Feb 28 01:40:19 2023 +0100
```

**Comment by viferga** [comment]
It seems Guix is down.

**Comment by ROCKTAKEY** [comment]
> By the way, it would be interesting to know what is your use case with this Docker image

I use this image for CI in GitLab. In addition, I sometimes want to use Guix in Docker image.

**Comment by ROCKTAKEY** [comment]
> Can you update the version from the readme too? In the docker command at the end.

OK, I will.

**Comment by ROCKTAKEY** [comment]
> Another thing I would like to know if after modifying this image, this repo still works: https://github.com/metacall/distributable-linux
I am letting this as a draft meanwhile this is not addressed.

I would like to add GitHub Actions to ensure the build of image and `metacall/distributable-linux`,  if you don't mind.
I will make another PR when you allow it.

**Comment by ROCKTAKEY** [comment]
Like below, we should probably use ci.guix.gnu.org instead of ftp.gnu.org.

https://github.com/PromyLOPh/guix-install-action/blob/v1/action.yml#L36

**Comment by viferga** [comment]
> ensure the build of image and `metacall/distributable-linux`, if you don't mind. I will make another PR when you allow it.

Yes, sure, go ahead.

**Comment by viferga** [comment]
> By the way, to specify the commit of "guix" channel temporarily, `guix pull --commit=COMMIT` seems to be better, because easily update to latest "guix" by `guix pull` when users need. Is there any idea about it?
> 
> Here is the part of output of `guix pull --help`:
> 
> ```
>       --commit=COMMIT    download the specified "guix" channel COMMIT
> ```

I use the channels.scm file for that. What they told me is to use a mirror when Guix is down, but I haven't tried yet. I was busy.

**Comment by viferga** [comment]
I just added a CI for PRs. And it seems if Guix works, let's check if your PR passes.

**Comment by ROCKTAKEY** [comment]
>Can you share link? Maybe we can add it to the readme if you want, like in a new section of use cases.

Our repository is [Guix-jp/channel](https://gitlab.com/guix-jp/channel/-/merge_requests/10). I was refering to [this repository](https://gitlab.com/spritely/guile-goblins/-/blob/main/.gitlab-ci.yml).

GitLab CI in our repository is still draft, just because guix style and guix lint return 0 even when warning or error is detected, although this image worked fine.

**Comment by ROCKTAKEY** [comment]
>I use the channels.scm file for that.

Putting `channels.scm` can be sometimes annoying because `guix pull` does not pull the latest commit, while using the `--commit` option has no effect on following `guix pull`.

**Pull request merged**
